language: minimal

git:
  depth: 3
  submodules: false

services:
  - docker

before_install:
  - make build

script:
  - make rpm-parity

# Required by docker containers
sudo: required

# Need to change permissions to upload files successfully
#before_deploy: sudo chown -R travis:travis rpmbuild

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  draft: true
  file_glob: true
  file: rpmbuild/RPMS/x86_64/*
  on:
    tags: true
