language: minimal

git:
  depth: 3
  submodules: false

services:
  - docker

before_install:
  - make build

script:
  - make rpm-parity

# Required by docker containers
sudo: required

deploy:
  provider: releases
  skip-cleanup: true
  github-token: $GH_TOKEN
  draft: true
  file_glob: true
  file: rpmbuild/RPMS/*.rpm
  on:
    tags: true
