# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "centos/7"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder ".", "/vagrant"

  # Copy configuration file to install all dependencies to 
  # build the Parity Ethereum client
  config.vm.provision "file", source: "deps.sh", destination: "/home/vagrant/deps.sh"
  config.vm.provision "shell", inline: "chmod +x /home/vagrant/deps.sh"
end
